# Generated by Django 5.1.7 on 2025-03-30 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.TextField(verbose_name="模型标识")),
                ("name", models.TextField(verbose_name="模型名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chat", "大语言模型"),
                            ("vision", "多模态模型"),
                            ("ocr", "文字识别"),
                            ("file", "文档理解"),
                            ("audio", "语音理解"),
                        ],
                        default="chat",
                        max_length=20,
                        verbose_name="模型类型",
                    ),
                ),
                ("context", models.TextField(verbose_name="模型描述")),
                ("cost", models.TextField(verbose_name="费用说明")),
                (
                    "api_endpoint",
                    models.CharField(
                        default="/api/vision/", max_length=255, verbose_name="接口路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "所有接口配置",
                "verbose_name_plural": "所有接口配置",
                "db_table": "ai_model_info",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="文件"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, max_length=255, verbose_name="文件名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "图片"),
                            ("audio", "音频"),
                            ("video", "视频"),
                            ("document", "文档"),
                            ("other", "其他"),
                        ],
                        editable=False,
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.IntegerField(verbose_name="文件大小(字节)")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME类型"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "多媒体资料",
                "verbose_name_plural": "多媒体资料",
                "db_table": "ai_app_uploadedfile",
                "ordering": ["-upload_time"],
            },
        ),
    ]
