# Generated by Django 5.1.6 on 2025-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDProductDiagnosisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.TextField(verbose_name='主曝光图商品信息')),
                ('search_performance', models.CharField(max_length=50, verbose_name='搜索表现总分')),
                ('traffic_acquisition', models.CharField(max_length=50, verbose_name='流量获取力')),
                ('traffic_conversion', models.CharField(max_length=50, verbose_name='流量承接力')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='上传日期')),
            ],
            options={
                'verbose_name': '京麦商品诊断',
                'verbose_name_plural': '京麦商品诊断',
                'db_table': 'jd_product_diagnosis_data',
                'ordering': ['-upload_date', 'product_info'],
            },
        ),
        migrations.CreateModel(
            name='JDSearchKeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.TextField(verbose_name='商品信息')),
                ('search_keyword', models.CharField(max_length=255, verbose_name='搜索词')),
                ('traffic_contribution', models.CharField(max_length=50, verbose_name='流量贡献占比')),
                ('keyword_rank', models.CharField(max_length=50, verbose_name='词下排名')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='上传日期')),
            ],
            options={
                'verbose_name': '京麦搜索词下表现',
                'verbose_name_plural': '京麦搜索词下表现',
                'db_table': 'jd_search_keyword_data',
                'ordering': ['-upload_date', 'product_info'],
            },
        ),
    ]
