# Generated by Django 5.1.6 on 2025-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_jdproductdiagnosisdata_jdsearchkeyworddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdproductdiagnosisdata',
            name='product_info',
            field=models.TextField(verbose_name='曝光图商品信息'),
        ),
    ]
