# Generated by Django 5.1.6 on 2025-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_alter_jdproductdiagnosisdata_product_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.TextField(blank=True, null=True, verbose_name='商品信息')),
                ('search_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='搜索词')),
                ('traffic_contribution', models.CharField(blank=True, max_length=50, null=True, verbose_name='流量贡献占比')),
                ('keyword_rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='词下排名')),
                ('main_exposure_product', models.TextField(blank=True, null=True, verbose_name='主曝光图商品')),
                ('search_performance', models.CharField(blank=True, max_length=50, null=True, verbose_name='搜索表现总分')),
                ('traffic_acquisition', models.CharField(blank=True, max_length=50, null=True, verbose_name='流量获取力')),
                ('traffic_conversion', models.CharField(blank=True, max_length=50, null=True, verbose_name='流量承接力')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='上传日期')),
            ],
            options={
                'verbose_name': '京东数据',
                'verbose_name_plural': '京东数据',
                'db_table': 'jd_data',
                'ordering': ['-upload_date'],
            },
        ),
    ]
