# Generated by Django 5.1.6 on 2025-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_jdbrandtraffic_jdcompetitionanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jddata',
            name='category',
            field=models.CharField(blank=True, choices=[('京麦商品搜索看板', '京麦商品搜索看板'), ('京准通行业大盘', '京准通行业大盘'), ('京准通其他数据', '京准通其他数据'), ('商智基本数据', '商智基本数据'), ('商智内容数据', '商智内容数据'), ('商智产品数据', '商智产品数据'), ('八爪鱼', '八爪鱼'), ('EasySpider', 'EasySpider')], max_length=50, null=True, verbose_name='数据类别'),
        ),
        migrations.AddField(
            model_name='jddata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jd_data/', verbose_name='数据文件'),
        ),
        migrations.AddField(
            model_name='jddata',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='子类别'),
        ),
        migrations.AlterField(
            model_name='jddata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
    ]
