# Generated by Django 5.1.6 on 2025-03-31 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0006_jddata_category_jddata_file_jddata_subcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JDDataDashboard',
            fields=[
            ],
            options={
                'verbose_name': '京麦数据看板',
                'verbose_name_plural': '京麦数据看板',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_app.jddata',),
        ),
        migrations.AlterModelOptions(
            name='jdbrandtraffic',
            options={'verbose_name': '京准通品牌流量总览', 'verbose_name_plural': '京准通品牌流量总览'},
        ),
        migrations.AlterModelOptions(
            name='jdcompetitionanalysis',
            options={'verbose_name': '京准通竞争分析数据', 'verbose_name_plural': '京准通竞争分析数据'},
        ),
        migrations.AlterModelOptions(
            name='jdcontenttypeanalysis',
            options={'verbose_name': '商智内容类型分析', 'verbose_name_plural': '商智内容类型分析'},
        ),
        migrations.AlterModelOptions(
            name='jdcorecontentdata',
            options={'verbose_name': '商智核心内容数据', 'verbose_name_plural': '商智核心内容数据'},
        ),
        migrations.AlterModelOptions(
            name='jdhotsearchwords',
            options={'verbose_name': '京准通热点搜索词排行', 'verbose_name_plural': '京准通热点搜索词排行'},
        ),
        migrations.AlterModelOptions(
            name='jdkeyworddata',
            options={'verbose_name': '京麦词下表现', 'verbose_name_plural': '京麦词下表现'},
        ),
        migrations.AlterModelOptions(
            name='jdmarketingoverview',
            options={'verbose_name': '京准通营销概况数据', 'verbose_name_plural': '京准通营销概况数据'},
        ),
        migrations.AlterModelOptions(
            name='jdmatrixanalysis',
            options={'verbose_name': '京准通矩阵分析数据', 'verbose_name_plural': '京准通矩阵分析数据'},
        ),
        migrations.AlterModelOptions(
            name='jdoveralldashboard',
            options={'verbose_name': '京准通整体看板数据', 'verbose_name_plural': '京准通整体看板数据'},
        ),
        migrations.AlterModelOptions(
            name='jdproductdiagnosis',
            options={'verbose_name': '京麦商品诊断数据', 'verbose_name_plural': '京麦商品诊断数据'},
        ),
        migrations.AlterModelOptions(
            name='jdrealtimedata',
            options={'verbose_name': '商智实时概况', 'verbose_name_plural': '商智实时概况'},
        ),
        migrations.AlterModelOptions(
            name='jdregionalanalysis',
            options={'verbose_name': '京准通地域分析数据', 'verbose_name_plural': '京准通地域分析数据'},
        ),
        migrations.AlterModelOptions(
            name='jdrisingsearchwords',
            options={'verbose_name': '京准通新秀搜索词排行', 'verbose_name_plural': '京准通新秀搜索词排行'},
        ),
        migrations.AlterModelOptions(
            name='jdsurgingsearchwords',
            options={'verbose_name': '京准通飙升搜索词排行', 'verbose_name_plural': '京准通飙升搜索词排行'},
        ),
        migrations.AlterModelOptions(
            name='jdtrafficdata',
            options={'verbose_name': '商智流量总览', 'verbose_name_plural': '商智流量总览'},
        ),
        migrations.AlterModelOptions(
            name='jdtransactiondata',
            options={'verbose_name': '商智交易概况', 'verbose_name_plural': '商智交易概况'},
        ),
        migrations.RenameField(
            model_name='jdsourceanalysis',
            old_name='conversion_amount',
            new_name='daily_guide_order_amount',
        ),
        migrations.RenameField(
            model_name='jdsourceanalysis',
            old_name='conversion_orders',
            new_name='daily_guide_order_count',
        ),
        migrations.RenameField(
            model_name='jdsourceanalysis',
            old_name='cart_users',
            new_name='guide_cart_users',
        ),
        migrations.RemoveField(
            model_name='jdmarketingoverview',
            name='click_time',
        ),
        migrations.RemoveField(
            model_name='jdmarketingoverview',
            name='cost_per_mille',
        ),
        migrations.RemoveField(
            model_name='jdmarketingoverview',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='jdmarketingoverview',
            name='total_order_lines',
        ),
        migrations.RemoveField(
            model_name='jdmatrixanalysis',
            name='cost_per_mille',
        ),
        migrations.RemoveField(
            model_name='jdmatrixanalysis',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='jdmatrixanalysis',
            name='direct_order_lines',
        ),
        migrations.RemoveField(
            model_name='jdmatrixanalysis',
            name='indirect_order_lines',
        ),
        migrations.RemoveField(
            model_name='jdmatrixanalysis',
            name='total_order_lines',
        ),
        migrations.RemoveField(
            model_name='jdoveralldashboard',
            name='transaction_rate',
        ),
        migrations.RemoveField(
            model_name='jdrealtimedata',
            name='avg_stay_time',
        ),
        migrations.RemoveField(
            model_name='jdrealtimedata',
            name='views_per_visitor',
        ),
        migrations.RemoveField(
            model_name='jdtrafficdata',
            name='avg_stay_time',
        ),
        migrations.RemoveField(
            model_name='jdtransactiondata',
            name='transaction_avg_price',
        ),
        migrations.RemoveField(
            model_name='jdtransactiondata',
            name='transaction_conversion_rate',
        ),
        migrations.RemoveField(
            model_name='jdtransactiondata',
            name='transaction_items',
        ),
        migrations.RemoveField(
            model_name='jdtransactiondata',
            name='transaction_orders',
        ),
        migrations.AddField(
            model_name='jdbrandtraffic',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='competitor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='竞品名称'),
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='avg_stay_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='人均停留时长'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='content_views',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内容浏览量'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='content_visitors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内容访客数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='daily_guide_order_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当日引导成交金额'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='daily_guide_order_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当日引导成交单量'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='daily_guide_order_users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当日引导成交人数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='guide_cart_times',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引导加购次数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='guide_cart_users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引导加购人数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='guide_detail_views',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引导进商详浏览量'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='guide_detail_visitors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引导进商详访客数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='new_content_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新增内容数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='new_content_sku_coverage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新增内容覆盖sku数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='online_content_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='在线内容数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='online_content_sku_coverage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='在线内容覆盖sku数'),
        ),
        migrations.AddField(
            model_name='jdcorecontentdata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdhotsearchwords',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdinventorydata',
            name='available_inventory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='可用库存'),
        ),
        migrations.AddField(
            model_name='jdinventorydata',
            name='in_stock_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='现货库存成本'),
        ),
        migrations.AddField(
            model_name='jdinventorydata',
            name='in_stock_inventory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='现货库存'),
        ),
        migrations.AddField(
            model_name='jdinventorydata',
            name='orderable_inventory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='可订购库存'),
        ),
        migrations.AddField(
            model_name='jdinventorydata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdkeyworddata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdmarketingoverview',
            name='campaign_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='投放时间'),
        ),
        migrations.AddField(
            model_name='jdmarketingoverview',
            name='cpm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='千次展现成本'),
        ),
        migrations.AddField(
            model_name='jdmarketingoverview',
            name='total_orders',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总订单行'),
        ),
        migrations.AddField(
            model_name='jdmarketingoverview',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdmatrixanalysis',
            name='cpm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='千次展现成本'),
        ),
        migrations.AddField(
            model_name='jdmatrixanalysis',
            name='direct_orders',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='直接订单行'),
        ),
        migrations.AddField(
            model_name='jdmatrixanalysis',
            name='indirect_orders',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='间接订单行'),
        ),
        migrations.AddField(
            model_name='jdmatrixanalysis',
            name='total_orders',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总订单行'),
        ),
        migrations.AddField(
            model_name='jdmatrixanalysis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdoctopusproductsearch',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdoveralldashboard',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdproductdiagnosis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdregionalanalysis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdrisingsearchwords',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdsourceanalysis',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdsurgingsearchwords',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdtrafficdata',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平均停留时长'),
        ),
        migrations.AddField(
            model_name='jdtrafficdata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='jdtransactiondata',
            name='average_order_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交客单价'),
        ),
        migrations.AddField(
            model_name='jdtransactiondata',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交转化率'),
        ),
        migrations.AddField(
            model_name='jdtransactiondata',
            name='order_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交单量'),
        ),
        migrations.AddField(
            model_name='jdtransactiondata',
            name='product_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交商品件数'),
        ),
        migrations.AddField(
            model_name='jdtransactiondata',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='jdbrandtraffic',
            name='click_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='jdbrandtraffic',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='jdbrandtraffic',
            name='main_brand_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主品牌名称'),
        ),
        migrations.AlterField(
            model_name='jdbrandtraffic',
            name='traffic_rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流量排名'),
        ),
        migrations.AlterField(
            model_name='jdbrandtraffic',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdcompetitionanalysis',
            name='data_content',
            field=models.TextField(blank=True, null=True, verbose_name='数据内容'),
        ),
        migrations.AlterField(
            model_name='jdcompetitionanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdcontenttypeanalysis',
            name='data_content',
            field=models.TextField(blank=True, null=True, verbose_name='数据内容'),
        ),
        migrations.AlterField(
            model_name='jdcontenttypeanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdcorecontentdata',
            name='content_data',
            field=models.TextField(blank=True, null=True, verbose_name='内容数据'),
        ),
        migrations.AlterField(
            model_name='jdcorecontentdata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='jdcorecontentdata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdhotsearchwords',
            name='competition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='竞争力'),
        ),
        migrations.AlterField(
            model_name='jdhotsearchwords',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='jdhotsearchwords',
            name='search_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='搜索指数'),
        ),
        migrations.AlterField(
            model_name='jdhotsearchwords',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdinventorydata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdkeyworddata',
            name='keyword_rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='词下排名'),
        ),
        migrations.AlterField(
            model_name='jdkeyworddata',
            name='traffic_contribution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流量贡献占比'),
        ),
        migrations.AlterField(
            model_name='jdkeyworddata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='avg_click_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平均点击成本'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='avg_order_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平均订单成本'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='click_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='clicks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='花费'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='impressions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='展现数'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='roi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='投产比'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='total_cart_adds',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总加购数'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='total_order_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总订单金额'),
        ),
        migrations.AlterField(
            model_name='jdmarketingoverview',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='avg_click_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平均点击成本'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='avg_order_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平均订单成本'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='cart_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加购率'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='click_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='click_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击时间'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='clicks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='花费'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='direct_cart_adds',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='直接加购数'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='direct_order_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='直接订单金额'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='impressions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='展现数'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='indirect_cart_adds',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='间接加购数'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='indirect_order_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='间接订单金额'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='product_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='roi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='投产比'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='total_cart_adds',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总加购数'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='total_order_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总订单金额'),
        ),
        migrations.AlterField(
            model_name='jdmatrixanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdoctopusproductsearch',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='cart_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加购指数'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='cart_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加购率'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='click_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击指数'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='click_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='click_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击时间'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='impression_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='展现指数'),
        ),
        migrations.AlterField(
            model_name='jdoveralldashboard',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdproductdiagnosis',
            name='main_exposure_product',
            field=models.TextField(blank=True, null=True, verbose_name='主曝光图商品'),
        ),
        migrations.AlterField(
            model_name='jdproductdiagnosis',
            name='search_performance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='搜索表现总分'),
        ),
        migrations.AlterField(
            model_name='jdproductdiagnosis',
            name='traffic_acquisition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流量获取力'),
        ),
        migrations.AlterField(
            model_name='jdproductdiagnosis',
            name='traffic_conversion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流量承接力'),
        ),
        migrations.AlterField(
            model_name='jdproductdiagnosis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='page_views',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='visitor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='访客数'),
        ),
        migrations.AlterField(
            model_name='jdregionalanalysis',
            name='click_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='jdregionalanalysis',
            name='conversion_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='jdregionalanalysis',
            name='impression_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='展现指数'),
        ),
        migrations.AlterField(
            model_name='jdregionalanalysis',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域名称'),
        ),
        migrations.AlterField(
            model_name='jdregionalanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdrisingsearchwords',
            name='competition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='竞争力'),
        ),
        migrations.AlterField(
            model_name='jdrisingsearchwords',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='jdrisingsearchwords',
            name='search_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='搜索指数'),
        ),
        migrations.AlterField(
            model_name='jdrisingsearchwords',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdsourceanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdsurgingsearchwords',
            name='competition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='竞争力'),
        ),
        migrations.AlterField(
            model_name='jdsurgingsearchwords',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='jdsurgingsearchwords',
            name='search_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='搜索指数'),
        ),
        migrations.AlterField(
            model_name='jdsurgingsearchwords',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdtrafficdata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='jdtrafficdata',
            name='page_views',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='jdtrafficdata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdtrafficdata',
            name='views_per_visitor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='人均浏览量'),
        ),
        migrations.AlterField(
            model_name='jdtrafficdata',
            name='visitor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='访客数'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='page_views',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='transaction_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='transaction_users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交人数'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdtransactiondata',
            name='visitor_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='访客数'),
        ),
        migrations.AlterModelTable(
            name='jdbrandtraffic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdcompetitionanalysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdcontenttypeanalysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdcorecontentdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdhotsearchwords',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdkeyworddata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdmarketingoverview',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdmatrixanalysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdoveralldashboard',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdproductdiagnosis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdrealtimedata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdregionalanalysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdrisingsearchwords',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdsurgingsearchwords',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdtrafficdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jdtransactiondata',
            table=None,
        ),
    ]
