# Generated by Django 5.1.6 on 2025-04-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0007_jddatadashboard_alter_jdbrandtraffic_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JDProductDiagnosisData',
        ),
        migrations.DeleteModel(
            name='JDSearchKeywordData',
        ),
    ]
