# Generated by Django 5.1.6 on 2025-04-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0009_jdtempupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdoctopusjingmaidata',
            options={'verbose_name': '八爪鱼京麦采集数据', 'verbose_name_plural': '八爪鱼京麦采集数据'},
        ),
        migrations.RemoveField(
            model_name='jdoctopusjingmaidata',
            name='data_content',
        ),
        migrations.RemoveField(
            model_name='jdoctopusjingmaidata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jdoctopusjingmaidata',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='cart_adds',
            field=models.IntegerField(blank=True, help_text='允许为空', null=True, verbose_name='加购'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='cart_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='加购率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='cart_to_transaction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='加购成交率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='cart_transaction_rate_beat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加购成交率打败相似店铺'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='customer_conversion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户转化指标'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='customer_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='客户数量'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='detail_views',
            field=models.IntegerField(blank=True, null=True, verbose_name='浏览商详'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='entry_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='进店率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='entry_rate_beat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='进店率打败相似店铺'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='jddata_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai_app.jddata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='new_customer_beat_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='新客数打败相似店铺百分率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='score_change',
            field=models.CharField(default=1, max_length=100, verbose_name='评分及升降分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='score_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分数和升降率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='shop_entries',
            field=models.IntegerField(blank=True, null=True, verbose_name='进店数'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='top_shop_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='top店铺类型'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='toplist_data',
            field=models.TextField(blank=True, null=True, verbose_name='toplist数据'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='transaction_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='成交数'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='transaction_rate_beat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交转化率打败相似店铺'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='view_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='浏览率'),
        ),
        migrations.AddField(
            model_name='jdoctopusjingmaidata',
            name='view_rate_beat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='浏览率打败相似店铺'),
        ),
        migrations.AlterField(
            model_name='jdoctopusjingmaidata',
            name='description',
            field=models.TextField(default=1, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdoctopusjingmaidata',
            name='indicator',
            field=models.CharField(default=1, max_length=255, verbose_name='指标'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='jdoctopusjingmaidata',
            table=None,
        ),
    ]
