# Generated by Django 5.1.6 on 2025-04-03 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0010_alter_jdoctopusjingmaidata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdcompetitionanalysis',
            options={'verbose_name': '京东竞争分析数据', 'verbose_name_plural': '京东竞争分析数据'},
        ),
        migrations.RemoveField(
            model_name='jdcompetitionanalysis',
            name='competitor_name',
        ),
        migrations.RemoveField(
            model_name='jdcompetitionanalysis',
            name='data_content',
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='brand_name',
            field=models.CharField(default=1, max_length=200, verbose_name='品牌名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='brand_type',
            field=models.CharField(choices=[('competitor', '竞品品牌'), ('industry', '行业品牌'), ('self', '自身品牌')], default=1, max_length=20, verbose_name='品牌类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='click_time',
            field=models.CharField(default=1, max_length=100, verbose_name='点击时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdcompetitionanalysis',
            name='impression_count',
            field=models.FloatField(default=1, verbose_name='展现量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdcompetitionanalysis',
            name='upload_date',
            field=models.DateTimeField(verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdcompetitionanalysis',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
            preserve_default=False,
        ),
    ]
