# Generated by Django 5.1.6 on 2025-04-03 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0011_alter_jdcompetitionanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdcontenttypeanalysis',
            options={'verbose_name': '京东内容类型分析数据', 'verbose_name_plural': '京东内容类型分析数据'},
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='date',
            field=models.CharField(default=1, max_length=50, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='guide_cart',
            field=models.FloatField(default=0, verbose_name='引导加购'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='guide_merchant',
            field=models.FloatField(default=0, verbose_name='引导进商'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='online_content_guide',
            field=models.FloatField(default=0, verbose_name='在线内容引导进商'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='same_day_guide',
            field=models.FloatField(default=0, verbose_name='当日引导'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='same_day_order',
            field=models.FloatField(default=0, verbose_name='当日引导成交单量'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='seven_day_guide',
            field=models.FloatField(default=0, verbose_name='7日引导成'),
        ),
        migrations.AddField(
            model_name='jdcontenttypeanalysis',
            name='seven_day_order',
            field=models.FloatField(default=0, verbose_name='7日引导成交单量'),
        ),
        migrations.AlterField(
            model_name='jdcontenttypeanalysis',
            name='content_type',
            field=models.CharField(default=1, max_length=50, verbose_name='内容类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdcontenttypeanalysis',
            name='upload_date',
            field=models.DateTimeField(verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdcontenttypeanalysis',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
            preserve_default=False,
        ),
    ]
