# Generated by Django 5.1.6 on 2025-04-03 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0012_alter_jdcontenttypeanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdrealtimedata',
            options={'verbose_name': '京东实时概况', 'verbose_name_plural': '京东实时概况'},
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='cart_items_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='cart_user_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='cart_user_count',
            field=models.IntegerField(default=0, verbose_name='加购客户数'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_cart_user_count',
            field=models.IntegerField(default=0, verbose_name='加购客户数(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_conversion_rate',
            field=models.FloatField(default=0, verbose_name='成交转化率(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_customer_price',
            field=models.FloatField(default=0, verbose_name='成交客单价(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_neg_cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数(负向)(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_order_amount',
            field=models.FloatField(default=0, verbose_name='成交金额(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_order_count',
            field=models.IntegerField(default=0, verbose_name='成交单量(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_page_views',
            field=models.IntegerField(default=0, verbose_name='浏览量(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_paid_count',
            field=models.IntegerField(default=0, verbose_name='成交人数(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_paid_items',
            field=models.IntegerField(default=0, verbose_name='成交商品件数(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_pos_cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数(正向)(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_uv_value',
            field=models.FloatField(default=0, verbose_name='UV价值(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='comp_visitor_count',
            field=models.IntegerField(default=0, verbose_name='访客数(对比日)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='conversion_rate',
            field=models.FloatField(default=0, verbose_name='成交转化率'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='conversion_rate_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='customer_price',
            field=models.FloatField(default=0, verbose_name='成交客单价'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='customer_price_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='neg_cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数(负向)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='neg_cart_items_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='order_amount',
            field=models.FloatField(default=0, verbose_name='成交金额'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='order_amount_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='order_count',
            field=models.IntegerField(default=0, verbose_name='成交单量'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='order_count_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='page_views_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='paid_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='paid_count',
            field=models.IntegerField(default=0, verbose_name='成交人数'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='paid_items',
            field=models.IntegerField(default=0, verbose_name='成交商品件数'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='paid_items_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='pos_cart_items',
            field=models.IntegerField(default=0, verbose_name='加购商品件数(正向)'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='pos_cart_items_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='uv_value',
            field=models.FloatField(default=0, verbose_name='UV价值'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='uv_value_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AddField(
            model_name='jdrealtimedata',
            name='visitor_compare',
            field=models.FloatField(default=0, verbose_name='较对比日'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='date',
            field=models.CharField(default=1, max_length=100, verbose_name='时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='page_views',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='upload_date',
            field=models.DateTimeField(verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdrealtimedata',
            name='visitor_count',
            field=models.IntegerField(default=0, verbose_name='访客数'),
        ),
    ]
