# Generated by Django 5.1.6 on 2025-04-03 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0013_alter_jdrealtimedata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdinfluenceranalysis',
            options={'verbose_name': '京东达人分析数据', 'verbose_name_plural': '京东达人分析数据'},
        ),
        migrations.RemoveField(
            model_name='jdinfluenceranalysis',
            name='cart_users',
        ),
        migrations.RemoveField(
            model_name='jdinfluenceranalysis',
            name='conversion_amount',
        ),
        migrations.RemoveField(
            model_name='jdinfluenceranalysis',
            name='conversion_orders',
        ),
        migrations.RemoveField(
            model_name='jdinfluenceranalysis',
            name='detail_visitors',
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='daily_guide_order_amount',
            field=models.FloatField(default=0, verbose_name='当日引导成交金额'),
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='daily_guide_order_count',
            field=models.IntegerField(default=0, verbose_name='当日引导成交单量'),
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='guide_cart_users',
            field=models.IntegerField(default=0, verbose_name='引导加购人数'),
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='guide_detail_visitors',
            field=models.IntegerField(default=0, verbose_name='引导进商详访客数'),
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='influencer_id',
            field=models.CharField(default=1, max_length=100, verbose_name='达人ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdinfluenceranalysis',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdinfluenceranalysis',
            name='date',
            field=models.CharField(default=1, max_length=100, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdinfluenceranalysis',
            name='influencer',
            field=models.CharField(default=1, max_length=100, verbose_name='达人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdinfluenceranalysis',
            name='influencer_name',
            field=models.CharField(default=1, max_length=100, verbose_name='达人名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdinfluenceranalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterModelTable(
            name='jdinfluenceranalysis',
            table=None,
        ),
    ]
