# Generated by Django 5.1.6 on 2025-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0014_alter_jdinfluenceranalysis_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdoctopusjingmaidata',
            old_name='customer_conversion',
            new_name='customer_metric',
        ),
        migrations.AlterField(
            model_name='jdoctopusjingmaidata',
            name='cart_adds',
            field=models.IntegerField(blank=True, null=True, verbose_name='加购'),
        ),
    ]
