# Generated by Django 5.1.6 on 2025-04-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0015_rename_customer_conversion_jdoctopusjingmaidata_customer_metric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdoctopusjingmaidata',
            name='toplist_data',
        ),
        migrations.CreateModel(
            name='JDShopRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='店铺名称')),
                ('ranking', models.IntegerField(verbose_name='排名')),
                ('ranking_type', models.CharField(max_length=50, verbose_name='排名类型')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('jingmai_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_rankings', to='ai_app.jdoctopusjingmaidata', verbose_name='关联京麦数据')),
            ],
            options={
                'verbose_name': '京东店铺排名',
                'verbose_name_plural': '京东店铺排名',
                'ordering': ['ranking_type', 'ranking'],
            },
        ),
    ]
