# Generated by Django 5.1.6 on 2025-04-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0016_remove_jdoctopusjingmaidata_toplist_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdeasyspiderdata',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Easy京麦采集', 'verbose_name_plural': 'Easy京麦采集'},
        ),
    ]
