# Generated by Django 5.1.6 on 2025-04-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0006_alter_jdeasyspiderdata_options'),
        ('ai_app', '0017_alter_jdeasyspiderdata_options'),
    ]

    operations = [
    ]
